version: 2
jobs:
    build:
        machine:
              circleci/classic:latest
        steps:
           - run: npm run rollup-build
           - run: URL="$(node_modules/.bin/now deploy --token=$ZEIT_TOKEN)"
           - run: node_modules/.bin/await-url "$URL" --tries=200
           - run: node_modules/.bin/now alias set "$URL" nedbailov.com --token=$ZEIT_TOKEN
           - run: node_modules/.bin/now remove nedbailov --yes --safe --token=$ZEIT_TOKEN || true
    
